<a href="https://colab.research.google.com/github/1nvento/Numpy-Assignment-/blob/arghya/Questions/Excercise%20numpy%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercises

1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [0]:
import numpy as np #import numpy

2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

In [12]:
a= np.array([1,2,3])
print(a)

[1 2 3]


3) Create an array of the first 10 odd integers.

In [13]:
b=np.arange(1,20,2)
print(b)

[ 1  3  5  7  9 11 13 15 17 19]


4) Find intersection of a and b

In [6]:
#expected output array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
common=set(a) & set(b)
print(common)



{2, 4}


5) Reshape 1d array a to 2d array of 2X5

In [8]:
a = np.arange(10)
b=a.reshape(2,5)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]


6) Create a numpy array to list and vice versa

In [10]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
b=np.array(a) #creating a array
print(b)
a=list(a) #creating a list
print(a)

[1 2 3 4 5 6 7 8 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.