# Numpy Exercises

1) Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions

In [3]:
import numpy as numpy
array=numpy.linspace(-1.3,2.5,64)
print(array)

[-1.3        -1.23968254 -1.17936508 -1.11904762 -1.05873016 -0.9984127
 -0.93809524 -0.87777778 -0.81746032 -0.75714286 -0.6968254  -0.63650794
 -0.57619048 -0.51587302 -0.45555556 -0.3952381  -0.33492063 -0.27460317
 -0.21428571 -0.15396825 -0.09365079 -0.03333333  0.02698413  0.08730159
  0.14761905  0.20793651  0.26825397  0.32857143  0.38888889  0.44920635
  0.50952381  0.56984127  0.63015873  0.69047619  0.75079365  0.81111111
  0.87142857  0.93174603  0.99206349  1.05238095  1.11269841  1.17301587
  1.23333333  1.29365079  1.35396825  1.41428571  1.47460317  1.53492063
  1.5952381   1.65555556  1.71587302  1.77619048  1.83650794  1.8968254
  1.95714286  2.01746032  2.07777778  2.13809524  2.1984127   2.25873016
  2.31904762  2.37936508  2.43968254  2.5       ]


2) Generate an array of length 3n filled with the cyclic pattern 1, 2, 3

In [62]:
import numpy as numpy
array=numpy.array([1,2,3])
print(array)
length=input("Enter the value of n such that the new array becomes of size 3n: ")
array=numpy.resize(array,(1,3*int(length)))
print (array)

[1 2 3]
Enter the value of n such that the new array becomes of size 3n: 4
[[1 2 3 1 2 3 1 2 3 1 2 3]]


3) Create an array of the first 10 odd integers.

In [56]:
import numpy as numpy
array=numpy.arange(1,20,2)
print(array)

[ 1  3  5  7  9 11 13 15 17 19]


4) Find intersection of a and b

In [61]:
import numpy as numpy
array1=numpy.array([1,2,3,4,5,6])
array2=numpy.array([5,6,7,8,9,10])
print(numpy.intersect1d(array1,array2))

[5 6]


5) Reshape 1d array a to 2d array of 2X5

In [66]:
import numpy as numpy
array1=numpy.array([10,20,30,40,50,60,70,80,90,100])
array2=numpy.reshape(array1,(2,5))
print(array2)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


6) Create a numpy array to list and vice versa

In [69]:
import numpy as numpy
array=numpy.array([10,20,30,40,50,60,70,80,90,100])
print(array.tolist())

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]


In [71]:
import numpy as numpy
list=[10,20,30,40,50,60,70,80,90,100]
array=numpy.array(list)
print(array)


[ 10  20  30  40  50  60  70  80  90 100]


7) Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [73]:
import numpy as numpy
array=numpy.zeros((10,10))
print("Original array of size 10x10:")
print(array)
print("Modified array after 'framing':")
array=numpy.pad(array,pad_width=1,constant_values=1)
print(array)

Original array of size 10x10:
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Modified array after 'framing':
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


8) Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [81]:
import numpy as numpy
array=numpy.ones((3,3))
print("The required checkerboard pattern is:")
array=numpy.zeros((8,8),dtype=int)
array[1::2,::2]=1
array[::2,1::2]=1
print(array)

The required checkerboard pattern is:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
